[package]
name = "zk_api_credits"
version = "0.1.0"
edition = "2024_07"

[[target.executable]]
name = "zk_api_credits"
function = "zk_api_credits::main"

[[target.executable]]
name = "zk_api_credits_v2_kernel"
function = "zk_api_credits::v2_kernel"

[[target.executable]]
name = "derive_rate_commitment_root"
function = "zk_api_credits::derive_rate_commitment_root"

[cairo]
enable-gas = false

[dependencies]
cairo_execute = "2.14.0"
openzeppelin_merkle_tree = "2.0.0"

[dev-dependencies]
cairo_test = "2.14.0"
